### ISSUE TITLE
mp4 files (and others) not served via /cms/

### ISSUE THREAD

**Issue by roerch** [django-daiquiri/dq-dev#9]
within 4MOST we do have Videos included in our news posts, which are currently not delivered from the webserver, creating an error on the console
```
dqdev-daiquiri-qmost    | Traceback (most recent call last):
dqdev-daiquiri-qmost    |   File "/home/dq/.local/lib/python3.9/site-packages/django_sendfile/utils.py", line 44, in _sanitize_path
dqdev-daiquiri-qmost    |     path_root = Path(getattr(settings, 'SENDFILE_ROOT', None))
dqdev-daiquiri-qmost    |   File "/usr/lib/python3.9/pathlib.py", line 1071, in __new__
dqdev-daiquiri-qmost    |     self = cls._from_parts(args, init=False)
dqdev-daiquiri-qmost    |   File "/usr/lib/python3.9/pathlib.py", line 696, in _from_parts
dqdev-daiquiri-qmost    |     drv, root, parts = self._parse_args(args)
dqdev-daiquiri-qmost    |   File "/usr/lib/python3.9/pathlib.py", line 680, in _parse_args
dqdev-daiquiri-qmost    |     a = os.fspath(a)
dqdev-daiquiri-qmost    | TypeError: expected str, bytes or os.PathLike object, not NoneType
dqdev-daiquiri-qmost    | 
dqdev-daiquiri-qmost    | During handling of the above exception, another exception occurred:
dqdev-daiquiri-qmost    | 
dqdev-daiquiri-qmost    | Traceback (most recent call last):
dqdev-daiquiri-qmost    |   File "/home/dq/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
dqdev-daiquiri-qmost    |     response = get_response(request)
dqdev-daiquiri-qmost    |   File "/home/dq/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
dqdev-daiquiri-qmost    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
dqdev-daiquiri-qmost    |   File "/home/dq/app/qmostcms/views.py", line 106, in render_file
dqdev-daiquiri-qmost    |     return send_file(request, file_path)
dqdev-daiquiri-qmost    |   File "/home/dq/source/daiquiri/files/utils.py", line 100, in send_file
dqdev-daiquiri-qmost    |     return sendfile(request, absolute_file_path)
dqdev-daiquiri-qmost    |   File "/home/dq/.local/lib/python3.9/site-packages/django_sendfile/utils.py", line 85, in sendfile
dqdev-daiquiri-qmost    |     filepath_obj = _sanitize_path(filename)
dqdev-daiquiri-qmost    |   File "/home/dq/.local/lib/python3.9/site-packages/django_sendfile/utils.py", line 46, in _sanitize_path
dqdev-daiquiri-qmost    |     raise ImproperlyConfigured('You must specify a value for SENDFILE_ROOT')
dqdev-daiquiri-qmost    | django.core.exceptions.ImproperlyConfigured: You must specify a value for SENDFILE_ROOT
dqdev-daiquiri-qmost    | [2023-02-22 08:56:52,909] "GET /cms/files/WFC_handling_1.mp4 HTTP/1.1" 500 132357
```
Found out that this is due to [docker/daiquiri/rootfs/home/dq/tpl/Caddyfile](https://github.com/django-daiquiri/dq-dev/commit/ee534acacd389f1ee0c39d9558d313d5def46617#diff-06042a0de9169899a75d930ea3eeeb232a45f4754e771ee67ad820fa16c912e8) not including the file type.
If it does not create other problems, I'd suggest to add at least bmp and mp4 files, which we currently also use.

**Comment by triole** [comment]
I close the issue because the mentioned file types should be supported by now. You can check below

https://github.com/django-daiquiri/dq-dev/blob/e9c8b8611360978d5c2957364220f2f2760aecba/docker/daiquiri/rootfs/home/dq/tpl/Caddyfile#L9
